name : build script for backend

on:
  push:
    branches:
      - main
    
jobs:
  build:
    name: Build the chess app backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd backend && npm install

      # -name: Generate Prisma Client
      #   run: npm run db:generate

      - name: Build the project
        run: npm run build