name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: akemnoorsingh/chess-backend:latest

      - name: Verify Pushed Image
        run: docker pull akemnoorsingh/chess-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull akemnoorsingh/chess-backend:latest
            sudo docker stop chess-backend || true
            sudo docker rm chess-backend || true
            sudo docker run -d --name chess-backend -p 3000:3000 --restart unless-stopped -e REDIS_USERNAME=${{ secrets.REDIS_USERNAME }} -e REDIS_PORT=${{ secrets.REDIS_PORT }} -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} -e REDIS_HOST=${{ secrets.REDIS_HOST }} akemnoorsingh/chess-backend:latest